spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${jdbcUser}
    password: ${jdbcPassword}
    url: ${jdbcUrl}
  liquibase:
    change-log: db/changelog/changelog-master.xml
  jpa:
    databasePlatform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddlAuto: update
    openInView: false
